apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonCR.annotations | nindent 4 }}    
  name: rfe-oci-build-auto-iso
spec:
  workspaces:
    - name: workspace
  params:
    - name: build-commit-id
      description: Commit ID of the RFE Installer Build
      type: string
    - name: image-builder-host
      description: Image Builder Host used for Pipeline Run
      type: string
    - name: image-builder-secret
      description: Name of the Secret Containing the SSH Key for the Image Builder Host
      default: "image-builder-ssh-key"
      type: string
    - name: kickstart-url
      description: URL Containing the Kickstart File
      type: string
  results:
    - name: iso-url
      description: URL Containing the Autobooting Image
  steps:
    - name: build-auto-iso-playbook
      image: {{ .Values.ansibleRunner.image | quote }}
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook \
            -u cloud-user \
            --private-key=/var/secrets/image-builder-ssh/ssh-privatekey \
            -e kickstart_url=$(params.kickstart-url) \
            -e build_commit_id=$(params.build-commit-id) \
            -e image_builder_host=$(params.image-builder-host) \
            -e nexus_credentials_secret_name={{ .Values.publicationEndpoints.artifactRepository.nexus.credentialsSecretName | quote }} \
            -e nexus_credentials_secret_namespace={{ .Values.publicationEndpoints.artifactRepository.nexus.credentialsSecretNamespace | quote }} \
            -e nexus_repository={{ .Values.publicationEndpoints.artifactRepository.nexus.autoIsoRepository | quote }} \
            -e nexus_http_scheme={{ .Values.publicationEndpoints.artifactRepository.nexus.httpScheme | quote }} \
            -e nexus_service_name={{ .Values.publicationEndpoints.artifactRepository.nexus.serviceName | quote }} \
            -e nexus_service_port={{ .Values.publicationEndpoints.artifactRepository.nexus.servicePort | quote }} \
            -e skip_nexus_upload={{ eq .Values.publicationEndpoints.artifactRepository.mode "disabled" | quote }} \
            -e httpd_route_name={{ .Values.publicationEndpoints.httpServing.routeName | quote }} \
            -e httpd_route_namespace={{ .Values.publicationEndpoints.httpServing.routeNamespace | quote }} \
            -e iso_url_output_file=$(results.iso-url.path) \
            playbooks/oci-build-auto-iso.yaml
      command:
        - /bin/bash
        - -c
      volumeMounts:
        - name: image-builder-ssh
          mountPath: /var/secrets/image-builder-ssh
          readOnly: true
  volumes:
    - name: image-builder-ssh
      secret:
        defaultMode: 0440
        secretName: "$(params.image-builder-secret)"
