deployment:
  mode: managed-rfe-argocd

permissions:
  mode: auto

components:
  gitops:
    mode: managed
    connection:
      namespace: rfe-gitops
      project: rfe
      server: https://kubernetes.default.svc
  odf:
    mode: byo
    connection:
      storageClassName: ocs-storagecluster-ceph-rbd
      objectBucketClaimStorageClassName: openshift-storage.noobaa.io
      bucketNamespace: rfe
