deployment:
  mode: byo-cluster-argocd

permissions:
  mode: auto

components:
  gitops:
    mode: byo
    connection:
      namespace: openshift-gitops
      project: rfe
      server: https://kubernetes.default.svc
      controllerServiceAccount: openshift-gitops-argocd-application-controller
    byo:
      createObjects: true
  odf:
    mode: byo
    connection:
      storageClassName: ocs-storagecluster-ceph-rbd
      objectBucketClaimStorageClassName: openshift-storage.noobaa.io
      bucketNamespace: rfe
    byo:
      createObjects: false
