apiVersion: v2
name: argocd-integration
description: ArgoCD control-plane integration resources
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
