---
defaultsConfigmap:
  annotations:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  timeoutMinutes: "180"

commonCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous

ansibleRunner:
  image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest

rhelTarget:
  major: 8
  architecture: x86_64
  imageBuilder:
    enabled: true
    ostreeRef: rhel/8/x86_64/edge
    composeTypes:
      container: rhel-edge-container
      installer: rhel-edge-installer
    repositories:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
  imageMode:
    enabled: false

publicationEndpoints:
  registry:
    mode: managed-reference
    imagePath: ""
    publisherSecretName: publisher
    setupSecretName: quay-rfe-setup
  artifactRepository:
    mode: managed-reference
    disabledResultValue: ""
    nexus:
      credentialsSecretName: nexus-rfe-credentials
      credentialsSecretNamespace: rfe
      serviceName: nexus
      servicePort: 8081
      httpScheme: http
      routeName: nexus
      routeNamespace: rfe
      kickstartRepository: rfe-kickstarts
      autoIsoRepository: rfe-auto-iso
  httpServing:
    mode: managed-reference
    routeName: httpd
    routeNamespace: rfe
    podNamespace: rfe
    podLabelSelector: deployment=httpd
    webRoot: /var/www/html
    stageServiceAccountName: oci-rfe-httpd

pipelines:
  repos:
    tooling:
      repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
      targetRevision: main
    blueprints:
      repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
      targetRevision: blueprints
    kickstarts:
      repoURL: https://github.com/redhat-cop/rhel-edge-automation-arch.git
      targetRevision: kickstarts
  additional_content_sources: |
    {
      "sources": {
      }
    }
